### ISSUE TITLE
同学，你的大作图挂啦！

### ISSUE THREAD

**Issue by LiangSiyv** [ZhouKanglei/ZhouKanglei.github.io#1]
![image](https://user-images.githubusercontent.com/18373310/144731305-bf3a1cbb-acc7-496f-8344-4b95bd0f67f7.png)

**Comment by LiangSiyv** [comment]
![image](https://user-images.githubusercontent.com/18373310/144731310-e6543382-f716-4d01-b13c-1517f8e5492d.png)

**Comment by ZhouKanglei** [comment]
可以在微信公众号看 https://mp.weixin.qq.com/s?__biz=MzUyMTE2NDYxMQ==&mid=2247489801&idx=1&sn=68c613b62d39b0b387676325b6ea260b&chksm=f9de1b25cea9923350841a90ae2d8637feb2700fa3be70978f28519bd56506a6c0f01689bc80&token=514611700&lang=zh_CN#rd

**Comment by LiangSiyv** [comment]
ook，就是提醒你一下
